version: '2'

services:
  recipes_front:
      container_name: recipes_front
      build:
        context: ./front
        args:
          - fotoLocation=${FOTO_LOCATION}
          - templocation=${TEMP_LOCATION}
      env_file:
        - '.env'
      ports:
        - "${NODE_PORT}:${NODE_PORT}"
      depends_on:
        - recipes_back
      links:
        - recipes_back
      volumes:
        - ./front/app:/usr/recipe/app

  recipes_back:
    container_name: recipes_back
    restart: always
    build: ./back
    ports:
      - "${API_PORT}:${API_PORT}"
      - 8000:8000
    depends_on:
      - recipes_db
    links:
      - recipes_db
    volumes:
       - ./${FOTO_LOCATION}:/usr/local/tomcat/webapps/ROOT/${FOTO_LOCATION}
       - ./${TEMP_LOCATION}:/usr/local/tomcat/webapps/ROOT/${TEMP_LOCATION}
    env_file:
       - '.env'

  recipes_db:
    container_name: recipes_db
    image: postgres:11.0
    volumes:
      - ./database/db:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=recipe
        - POSTGRES_PASSWORD=recipe
        - POSTGRES_DB=recipe
